"""
Workflow Engine — enables any profession or multi-step process to be
handled by Aria through composable, declarative workflows.

A Workflow is a sequence of Steps that can:
  - Call agents (researcher, planner, finance, etc.)
  - Execute tools directly
  - Branch conditionally
  - Loop over items
  - Collect user input
  - Produce layout directives for the frontend

Workflows can be:
  1. Pre-defined (registered in WORKFLOWS registry)
  2. Dynamically generated by the planner agent based on user request
"""

from dataclasses import dataclass, field
from typing import Any, Optional
from enum import Enum


class StepType(str, Enum):
    AGENT = "agent"           # Route to a specific agent
    TOOL = "tool"             # Call a tool directly
    CONDITION = "condition"   # Branch based on context
    LOOP = "loop"             # Iterate over items
    TRANSFORM = "transform"   # Transform/format data
    INPUT = "input"           # Request user input
    LAYOUT = "layout"         # Set the dashboard layout
    PARALLEL = "parallel"     # Run multiple steps concurrently


@dataclass
class WorkflowStep:
    id: str
    type: StepType
    name: str
    description: str = ""

    # For AGENT steps
    agent_name: Optional[str] = None
    prompt_template: Optional[str] = None

    # For TOOL steps
    tool_name: Optional[str] = None
    tool_args: Optional[dict] = None

    # For CONDITION steps
    condition: Optional[str] = None       # Python expression evaluated against context
    if_true: Optional[str] = None         # step_id to jump to
    if_false: Optional[str] = None        # step_id to jump to

    # For LOOP steps
    items_key: Optional[str] = None       # key in context holding the list
    body_step: Optional[str] = None       # step_id to execute for each item

    # For TRANSFORM steps
    transform_fn: Optional[str] = None    # dotted path to transform function

    # For LAYOUT steps
    layout_type: Optional[str] = None
    layout_title: Optional[str] = None

    # For PARALLEL steps
    parallel_steps: list[str] = field(default_factory=list)

    # Flow control
    next_step: Optional[str] = None       # next step_id (None = end)
    output_key: Optional[str] = None      # store result in context[output_key]


@dataclass
class Workflow:
    id: str
    name: str
    description: str
    category: str                         # profession / domain
    trigger_keywords: list[str]           # keywords that activate this workflow
    steps: list[WorkflowStep]
    required_context: list[str] = field(default_factory=list)   # context keys needed
    output_layout: str = "chat"           # default output layout

    @property
    def first_step(self) -> Optional[WorkflowStep]:
        return self.steps[0] if self.steps else None

    def get_step(self, step_id: str) -> Optional[WorkflowStep]:
        for step in self.steps:
            if step.id == step_id:
                return step
        return None


# ── Workflow Registry ─────────────────────────────────────

WORKFLOWS: dict[str, Workflow] = {}


def register_workflow(workflow: Workflow):
    WORKFLOWS[workflow.id] = workflow
    return workflow


def find_workflow(user_message: str) -> Optional[Workflow]:
    """Find a matching workflow based on user message keywords."""
    msg_lower = user_message.lower()
    best_match = None
    best_score = 0

    for wf in WORKFLOWS.values():
        score = sum(1 for kw in wf.trigger_keywords if kw in msg_lower)
        if score > best_score:
            best_score = score
            best_match = wf

    return best_match if best_score > 0 else None


# ══════════════════════════════════════════════════════════
# Pre-defined Workflows
# ══════════════════════════════════════════════════════════

# ── Real Estate Agent Workflow ────────────────────────────
register_workflow(Workflow(
    id="real_estate_search",
    name="Property Search",
    description="Search for properties, compare listings, and analyze deals",
    category="real_estate",
    trigger_keywords=["property", "house", "apartment", "real estate", "listing", "rent", "buy home"],
    output_layout="search_results",
    steps=[
        WorkflowStep(
            id="search", type=StepType.AGENT, name="Search Properties",
            agent_name="researcher",
            prompt_template="Search for real estate listings: {user_message}. Find properties with prices, locations, specs.",
            output_key="search_results", next_step="compare",
        ),
        WorkflowStep(
            id="compare", type=StepType.AGENT, name="Compare & Analyze",
            agent_name="finance",
            prompt_template="Analyze these property options and compare affordability: {search_results}",
            output_key="analysis", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Show Results",
            layout_type="comparison", layout_title="Property Comparison",
        ),
    ],
))

# ── Doctor/Patient Management Workflow ────────────────────
register_workflow(Workflow(
    id="health_assessment",
    name="Health Assessment",
    description="Track symptoms, suggest remedies, manage health records",
    category="healthcare",
    trigger_keywords=["symptoms", "diagnosis", "health check", "medical", "doctor", "patient"],
    output_layout="dashboard",
    steps=[
        WorkflowStep(
            id="gather", type=StepType.AGENT, name="Gather Health Info",
            agent_name="health",
            prompt_template="Based on the user's query: {user_message}. Check their health profile and provide guidance.",
            output_key="health_info", next_step="research",
        ),
        WorkflowStep(
            id="research", type=StepType.AGENT, name="Research",
            agent_name="researcher",
            prompt_template="Find current medical information about: {health_info}",
            output_key="research_results", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Health Dashboard",
            layout_type="dashboard", layout_title="Health Overview",
        ),
    ],
))

# ── Project Manager Workflow ──────────────────────────────
register_workflow(Workflow(
    id="project_management",
    name="Project Management",
    description="Break down projects, assign tasks, track progress",
    category="project_management",
    trigger_keywords=["project plan", "sprint", "milestone", "project board", "track project", "project status"],
    output_layout="kanban",
    steps=[
        WorkflowStep(
            id="plan", type=StepType.AGENT, name="Create Plan",
            agent_name="planner",
            prompt_template="Break down this project into actionable tasks with priorities and deadlines: {user_message}",
            output_key="project_plan", next_step="organize",
        ),
        WorkflowStep(
            id="organize", type=StepType.TRANSFORM, name="Organize Tasks",
            transform_fn="app.workflows.transforms.plan_to_kanban",
            output_key="kanban_data", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Project Board",
            layout_type="kanban", layout_title="Project Board",
        ),
    ],
))

# ── Daily Schedule Workflow ───────────────────────────────
register_workflow(Workflow(
    id="daily_schedule",
    name="Daily Schedule",
    description="View, plan, and manage daily/weekly schedule",
    category="productivity",
    trigger_keywords=["my schedule", "my day", "my week", "calendar", "what's on today", "plan my day", "agenda"],
    output_layout="calendar",
    steps=[
        WorkflowStep(
            id="fetch", type=StepType.TOOL, name="Fetch Reminders",
            tool_name="memory_search", tool_args={"query": "schedule events reminders appointments"},
            output_key="existing_events", next_step="plan",
        ),
        WorkflowStep(
            id="plan", type=StepType.AGENT, name="Plan Schedule",
            agent_name="planner",
            prompt_template="Help with the user's schedule request: {user_message}. Existing events: {existing_events}",
            output_key="schedule", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Calendar View",
            layout_type="calendar", layout_title="Your Schedule",
        ),
    ],
))

# ── Financial Review Workflow ─────────────────────────────
register_workflow(Workflow(
    id="financial_review",
    name="Financial Review",
    description="Analyze spending, track budget, financial planning",
    category="finance",
    trigger_keywords=["budget review", "spending", "financial overview", "money summary", "expense report", "financial details"],
    output_layout="finance",
    steps=[
        WorkflowStep(
            id="gather", type=StepType.TOOL, name="Fetch Financial Data",
            tool_name="memory_search", tool_args={"query": "budget expenses income spending financial"},
            output_key="financial_data", next_step="analyze",
        ),
        WorkflowStep(
            id="analyze", type=StepType.AGENT, name="Analyze Finances",
            agent_name="finance",
            prompt_template="Provide a comprehensive financial analysis: {user_message}. Data: {financial_data}",
            output_key="analysis", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Finance Dashboard",
            layout_type="finance", layout_title="Financial Overview",
        ),
    ],
))

# ── Product Research Workflow ─────────────────────────────
register_workflow(Workflow(
    id="product_research",
    name="Product Research",
    description="Search, compare, and recommend products",
    category="shopping",
    trigger_keywords=["find product", "best laptop", "compare phones", "shopping", "recommend", "buy", "deal"],
    output_layout="search_results",
    steps=[
        WorkflowStep(
            id="search", type=StepType.AGENT, name="Search Products",
            agent_name="researcher",
            prompt_template="Search for products matching: {user_message}. Find specs, prices, reviews, and deals.",
            output_key="products", next_step="compare",
        ),
        WorkflowStep(
            id="compare", type=StepType.AGENT, name="Compare Options",
            agent_name="finance",
            prompt_template="Compare these products and recommend the best value: {products}",
            output_key="comparison", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Show Results",
            layout_type="search_results", layout_title="Product Results",
        ),
    ],
))

# ── Content Creation Workflow ─────────────────────────────
register_workflow(Workflow(
    id="content_creation",
    name="Content Creation",
    description="Write articles, blog posts, social media content",
    category="writing",
    trigger_keywords=["write article", "blog post", "social media", "content", "draft", "write about"],
    output_layout="document",
    steps=[
        WorkflowStep(
            id="research", type=StepType.AGENT, name="Research Topic",
            agent_name="researcher",
            prompt_template="Research the topic for content creation: {user_message}",
            output_key="research", next_step="write",
        ),
        WorkflowStep(
            id="write", type=StepType.AGENT, name="Write Content",
            agent_name="writer",
            prompt_template="Write the content based on: {user_message}. Research: {research}",
            output_key="content", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Document View",
            layout_type="document", layout_title="Content Draft",
        ),
    ],
))

# ── Legal Research Workflow ───────────────────────────────
register_workflow(Workflow(
    id="legal_research",
    name="Legal Research",
    description="Research legal topics, contracts, compliance",
    category="legal",
    trigger_keywords=["legal", "contract", "law", "compliance", "regulation", "rights", "lawsuit"],
    output_layout="document",
    steps=[
        WorkflowStep(
            id="research", type=StepType.AGENT, name="Legal Research",
            agent_name="researcher",
            prompt_template="Research the legal topic: {user_message}. Find relevant laws, precedents, and guidelines.",
            output_key="research", next_step="analyze",
        ),
        WorkflowStep(
            id="analyze", type=StepType.AGENT, name="Legal Analysis",
            agent_name="writer",
            prompt_template="Provide a structured legal analysis of: {research}. Include key points, risks, and recommendations.",
            output_key="analysis", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Legal Brief",
            layout_type="document", layout_title="Legal Analysis",
        ),
    ],
))

# ── Education/Study Workflow ──────────────────────────────
register_workflow(Workflow(
    id="study_plan",
    name="Study Plan",
    description="Create study plans, explain topics, quiz preparation",
    category="education",
    trigger_keywords=["study", "learn", "explain", "teach me", "course", "exam", "quiz", "homework"],
    output_layout="document",
    steps=[
        WorkflowStep(
            id="research", type=StepType.AGENT, name="Research Topic",
            agent_name="researcher",
            prompt_template="Research educational content about: {user_message}",
            output_key="material", next_step="plan",
        ),
        WorkflowStep(
            id="plan", type=StepType.AGENT, name="Create Study Plan",
            agent_name="planner",
            prompt_template="Create a structured study plan for: {user_message}. Material: {material}",
            output_key="study_plan", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Study Dashboard",
            layout_type="timeline", layout_title="Study Plan",
        ),
    ],
))

# ── Travel Planning Workflow ──────────────────────────────
register_workflow(Workflow(
    id="travel_planning",
    name="Travel Planning",
    description="Plan trips, find flights, hotels, itineraries",
    category="travel",
    trigger_keywords=["travel", "trip", "flight", "hotel", "vacation", "itinerary", "visit"],
    output_layout="timeline",
    steps=[
        WorkflowStep(
            id="search", type=StepType.AGENT, name="Search Options",
            agent_name="researcher",
            prompt_template="Search for travel options: {user_message}. Find flights, hotels, and activities.",
            output_key="options", next_step="plan",
        ),
        WorkflowStep(
            id="plan", type=StepType.AGENT, name="Create Itinerary",
            agent_name="planner",
            prompt_template="Create a detailed travel itinerary: {user_message}. Options: {options}",
            output_key="itinerary", next_step="budget",
        ),
        WorkflowStep(
            id="budget", type=StepType.AGENT, name="Budget Analysis",
            agent_name="finance",
            prompt_template="Analyze the travel budget for: {itinerary}",
            output_key="budget", next_step="display",
        ),
        WorkflowStep(
            id="display", type=StepType.LAYOUT, name="Trip Plan",
            layout_type="timeline", layout_title="Travel Itinerary",
        ),
    ],
))
